name: 'Galasa CLI tool'
description: 'A GitHub Action that allows you to run the galasactl CLI tool'
inputs:
  galasactl_version:
    description: 'The version of galasactl to run, defaults to latest'
    required: false
    default: 'latest'
  galasactl_args:
    description: 'Arguments to pass into galasactl'
    required: false
  script:
    description: 'A script of commands that may use galasactl'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
